version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 enfund.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=enfund.settings
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"